### ISSUE TITLE
Feature Request: Load Static Database File from Hosting Server

### ISSUE THREAD

**Issue by aizimmer** [antelle/keeweb#73] opened 2015-12-28 12:15 UTC
I love what you got here, by the way. My question is if there is a simple way for me to edit your html file to just automatically open a database that is on a headless server serving the html file? I understand HTTP support is far down the road, but being aple to use it to simply serve a database file on its own filesystem would provide me with everything I am looking for. It would essentially become it's own KeePass server! LDAP integration is even possible with nginx or apache ldap mods.

**Comment by antelle** [comment] 2015-12-29 10:28
For now, there's no simple way to do this... Will be implemented after v1 release. Closing as duplicate of #15.

**Closed by antelle** 2015-12-29 10:28 UTC
