### ISSUE TITLE
save file cannot work in mac

### ISSUE THREAD

**Issue by jk2K** [antelle/keeweb#22] opened 2015-11-09 06:35 UTC
the sync icon is always show when i press `⌘+s`

![image](https://cloud.githubusercontent.com/assets/4025839/11027240/56a8836c-86ee-11e5-99d1-1f9a24202b9f.png)

KeeWeb v0.1.1 (built at 2015-11-04)
Environment: electron v0.34.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/0.1.1 Chrome/45.0.2454.85 Electron/0.34.0 Safari/537.36

**Comment by antelle** [comment] 2015-11-09 06:41
Duplicate of #21, the fix will be in v0.2 which will happen soon

**Closed by antelle** 2015-11-09 06:41 UTC
Labels: bug, duplicate, storage
