### ISSUE TITLE
Can't select list entry

### ISSUE THREAD

**Issue by Dragony** [antelle/keeweb#101] opened 2016-02-24 11:00 UTC
Hey there!

First off, awesome work creating keeweb. It's exactly what I've been looking for :)

I tried self hosting it today, but sadly I can't select an Entry from the list view. Every time I click an Item, I get the following error message: Uncaught TypeError: Cannot read property 'direction' of null.

I'm using the most recent Chrome (48) and the following version of the built source:
https://github.com/antelle/keeweb/commit/2bbc61c2f5a54ece9904726706f0efd467c74c6e

You can find the App here:
https://wasd.ch/pass

Let me know if I can provide you with more information that would help.

**Comment by antelle** [comment] 2016-02-24 11:13
Hello, 
Please describe the issue with more details, so I would be able to reproduce and fix it: 
- where do you click - just in the list with entries?
- does it repeat on Demo database (button Demo on start page)?
- have you changed any app settings? which, if yes?

If it doesn't repeat on Demo and the db you are using is private, so it cannot be pasted here:
- please bring up devtools, repeat this and expand the message, to get the stack trace

I've tried to open demo db on your server and it works for me ok.

**Comment by antelle** [comment] 2016-02-26 17:12
Closing until more info is provided.

**Closed by antelle** 2016-02-26 17:12 UTC
Labels: bug, need info
