### ISSUE TITLE
no carriage return ?

### ISSUE THREAD

**Issue by chantoine** [antelle/keeweb#124] opened 2016-02-26 18:55 UTC
Hi,

I frequently have a "notes" field with "a lot" of text.
The edit capabilities seem limited.
For example, how can i do a "carriage return" while editing that sort of field ?

Thanks !

KeeWeb v1.0.4 (a6e7afe, 2016-02-25)
Environment: web
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:38.9) Gecko/20100101 Goanna/2.0 Firefox/38.9 PaleMoon/26.1.1

**Comment by antelle** [comment] 2016-02-26 18:57
duplicate of #107

**Closed by antelle** 2016-02-26 18:57 UTC
Labels: bug, duplicate

**Comment by chantoine** [comment] 2016-02-26 19:00
Sorry, i searched and didn't find it.
Great, thanks !
