### ISSUE TITLE
Support KeePassRPC

### ISSUE THREAD

**Issue by eikaramba** [antelle/keeweb#84] opened 2016-02-13 15:34 UTC
One killer feature of KeePass is actually the possibility to integrate it into the browser via plugins (e.g. [keefox](https://addons.mozilla.org/de/firefox/addon/keefox/) on firefox). This is done via the [KeePassRPC ](https://github.com/luckyrat/KeeFox/tree/master/KeePassRPC)plugin. It would be great if this is supported, as Keeweb is a great desktop client IMHO (actually my personal favorite is the possibility to search within multiple files at once[we use keepass in the company and i use it personally]

**Comment by antelle** [comment] 2016-02-13 15:44
:sparkles:  integration with browser plugins will be implemented, most probably KeePassRPC or KeePassHTTP will be supported natively by app or as a built-in plugin
closing as duplicate of #4

**Closed by antelle** 2016-02-13 15:44 UTC
Labels: browser-plugins, duplicate, enhancement

**Comment by r0bbie** [comment] 2016-11-24 16:15
While this was closed as a duplicate of #4, which relates to Chrome autofill support specifically, I'd just like to add my hope to see this implemented in order to provide support for autofill on Firefox specifically (via [KeeFox](https://github.com/luckyrat/KeeFox)).

**Comment by vjooris** [comment] 2017-11-25 17:28
can we expect keeweb to be compatible with KeeFox. As KeeWeb is the only solution I found to open my Keepass files on a MAC.
Thank you

**Comment by antelle** [comment] 2017-11-25 17:31
@vjooris there are some other Firefox plugins, keefox is not the only one. If they're compatible with keepass-http, they can be used with keeweb as well.

**Comment by vjooris** [comment] 2017-11-25 21:05
ok thank you I'll continue searching in that direction

**Comment by antelle** [comment] 2017-11-25 21:05
Some of them are listed here: https://github.com/keeweb/keeweb/issues/781#issuecomment-346173376

**Comment by vjooris** [comment] 2017-11-25 21:08
oh thank you !
