### ISSUE TITLE
[Feature Request] OneDrive Support

### ISSUE THREAD

**Issue by wenLiangcan** [antelle/keeweb#106] opened 2016-02-25 15:59 UTC
I'm using the KeePass official app with [KeePassOneDriveSync](https://github.com/KoenZomers/KeePassOneDriveSync) plugin on Windows. But most of the time I work on Linux and that plugin doesn't support Linux. It would be nice if keeweb can add OneDrive support as a cross platform application.

**Comment by KapuzenSohn** [comment] 2016-02-25 16:19
Look at #14

**Comment by antelle** [comment] 2016-02-25 16:22
duplicate of #14

**Closed by antelle** 2016-02-25 16:22 UTC
