### ISSUE TITLE
Feature Request: additional Multiline fields

### ISSUE THREAD

**Issue by port22** [antelle/keeweb#238] opened 2016-06-02 17:31 UTC
Hi all,
I would also like to collect my code snippets with keeweb using the "more..." - fields, but they cut all newline characters and trim whitespaces/tabs.
Any chance to get that considered in a future version? :-)

**Comment by antelle** [comment] 2016-06-02 17:44
duplicate of #107

**Closed by antelle** 2016-06-02 17:44 UTC
