### ISSUE TITLE
[Feature request] Setting to choose if passwords are visible or not by default

### ISSUE THREAD

**Issue by frode** [antelle/keeweb#85] opened 2016-02-15 12:42 UTC
A setting for "Passwords are visible by default" to switch on/off should be added. 

I do not want all passwords to be visible by default, many times i simply want to access the app, select copy password and paste it into a sign in form, and if a friend or colleague is with me, I do not want passwords to be visible..

If passwords are set to not be visible, field value should just display as a fixed number of dots.

**Comment by antelle** [comment] 2016-02-15 12:47
Hm, passwords are displayed as dots by default, are they visible for you? Which version are you using? This may be a bug. Does it repeat on Demo db?

**Comment by frode** [comment] 2016-02-15 12:50
@antelle Does not repeat on demo db.. running Version 1.0.1 (feb8b2f) on Mac.

**Comment by antelle** [comment] 2016-02-15 12:51
So, it's a db-specific bug. Are there any errors in console? You can open it with Settings/General/Advanced.

**Comment by frode** [comment] 2016-02-15 12:55
No errors in console, only info on update checking and file loading info etc.

**Comment by antelle** [comment] 2016-02-15 12:57
That's a bit weird. Is it the same for all entries in your db or just some of them? If you create an entry with the same parameters, e.g. in a new db - does it behave in the same way?

**Comment by frode** [comment] 2016-02-15 12:59
Seems like all the entries i created in the db with MacPass/existing ones are visible, new ones display correctly as dots

**Comment by antelle** [comment] 2016-02-15 13:04
Hmm, looks like it's a problem of MacPass, I'll investigate this later today.
If you want to help and speed up the fix, please do the following: 
- export your DB to XML (click it in footer and press the button)
- format the XML, e.g. with tidy or some text editor
- find: 
 - `KeePassFile/Meta/MemoryProtection` section
 - `Entry` which corresponds to your entry, and inside it `Strings` where `Key` = `Password`, the value must be `<Value ProtectInMemory="True">...</Value>`

Password is one of fields belonging to entry, it can be either protected, or not protected. Looks like MacPass writes passwords NOT protected.

**Comment by frode** [comment] 2016-02-15 13:13
There is a <ProtectPassword>True</ProtectPassword> inside the MemoryProtection section of the exported xml

**Comment by antelle** [comment] 2016-02-15 13:14
And inside the entry?

**Comment by frode** [comment] 2016-02-15 13:16
There is not a tag named `ProtectInMemory` with a value..

**Comment by antelle** [comment] 2016-02-15 13:18
So yes, it's MacPass bug: passwords must be protected.
To overcome this, I'll add a special handling for passwords: event if are written by some apps as non-protected, they will be displayed as dots.

**Comment by frode** [comment] 2016-02-15 13:19
Thanks, sounds like a good plan as a workaround

**Comment by antelle** [comment] 2016-02-15 21:53
Just downloaded the latest MacPass 0.6.1 and created a new file with it: passwords are shown as dots in keeweb. Most probably the bug has been already fixed, so it's specific file issue. I hope I'll fix it shortly and make an update for your specific file.

**Comment by frode** [comment] 2016-02-16 07:44
I updated to the latest (alpha release 0.6.1) and it made all my passwords hidden by default in keeweb after a save to the db. Guess later versions fixes the missing attribute :+1:

**Comment by antelle** [comment] 2016-02-16 07:45
So the issue is resolved for you, right?

**Comment by frode** [comment] 2016-02-16 07:46
Yep!

**Comment by antelle** [comment] 2016-02-16 07:59
Ok, I'm closing it, as re-saving the db from macpass fixes unprotected passwords.

**Closed by antelle** 2016-02-16 07:59 UTC
Labels: bug

**Comment by frode** [comment] 2016-02-16 08:01
:+1:
