### ISSUE TITLE
[Feature request] S/FTP sync support

### ISSUE THREAD

**Issue by KevinSeroux** [antelle/keeweb#164] opened 2016-03-16 21:17 UTC
Hello,

First of all, I really appreciate your work. I don't like the implementations of KeePass for Linux but this software is very promising. However there is one reason why I still use the default KeePass with Wine. This is the SFTP sync. It allows me to ensure that I've the same database between my phone (with keepass2android) and my computers and that the database file is stored on a trustful server.

I think this is a complex feature to implement and I'll understand that you're not interested in this feature for the moment. But I wished to express a need that could be common.

Thanks and kind regards...

**Comment by antelle** [comment] 2016-03-16 21:22
duplicate of #103 
v1.1 will have webdav. later versions might have sftp support as well. but only desktop of course, not web.

**Closed by antelle** 2016-03-16 21:22 UTC
Labels: duplicate

**Comment by KevinSeroux** [comment] 2016-03-16 21:36
Thanks and sorry for the duplicated (forgot to search).

**Comment by antelle** [comment] 2016-03-16 21:37
It's okay. If you want, you can subscribe to that issue, to be notified of updates.
