### ISSUE TITLE
Idea: Windows Universal App

### ISSUE THREAD

**Issue by le717** [antelle/keeweb#184] opened 2016-04-09 17:00 UTC
Because this is written in JavaScript, would it be possible to use [WinJS](https://developer.microsoft.com/en-us/windows/develop/winjs) to build a Windows Universal app version? I just switched to Windows Phone and am looking for a KeePass app when I came across your awesome project here. It'd be nice to have an app so I can always access my passwords (or at least ensure the web app will work without a WiFI/data connection). :)

**Comment by antelle** [comment] 2016-04-09 17:11
This is a duplicate of #6
Implementing this will involve rewriting a part of functional especially for Windows, which will be not usable for other platforms. According to platform priorities, this is out of scope, unless we get extra finance for native mobile apps. It's better to use phonegap for this, to make the mobile code common.

**Closed by antelle** 2016-04-09 17:11 UTC
Labels: duplicate, mobile, windows
